# Generated by Django 4.2.6 on 2023-10-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.CharField(choices=[('i9', 'i9 10900K'), ('i5', 'i5 10900K'), ('i3', 'i3 10900K')], help_text='CPU', max_length=100),
        ),
    ]
