# Generated by Django 4.2.6 on 2023-12-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(help_text='Descrição', max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.IntegerField(default=0),
        ),
    ]
