# Generated by Django 4.2.6 on 2023-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_produto_descricao_alter_usuario_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(help_text='Descrição', max_length=500),
        ),
    ]
