# Generated by Django 4.2.6 on 2023-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_pc_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.CharField(help_text='CPU', max_length=100),
        ),
    ]
