# Generated by Django 4.2.6 on 2024-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_alter_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('c', 'Computador'), ('p', 'Periférico')], default='c', help_text='Categoria do produto', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
