# Generated by Django 4.2.6 on 2023-10-23 22:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_alter_pc_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=100)),
                ('descricao', models.CharField(help_text='Descrição', max_length=100)),
                ('preco', models.CharField(help_text='Preço', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID do produto', primary_key=True, serialize=False)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda.produto')),
            ],
        ),
    ]
