# Generated by Django 4.2.6 on 2023-10-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_produto_instanciaproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='id',
        ),
        migrations.AddField(
            model_name='pc',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda.produto'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='nome',
            field=models.CharField(help_text='Nome', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(help_text='Preço', max_length=100),
        ),
    ]
