# Generated by Django 4.2.6 on 2024-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_remove_usuario_celular_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='profiles_img/perfil.png', upload_to='profiles_img/'),
        ),
    ]
