# Generated by Django 4.2.6 on 2023-10-24 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_remove_pc_id_pc_produto_alter_pc_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='nome',
        ),
        migrations.AddField(
            model_name='pc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False),
        ),
    ]
