# Generated by Django 4.2.6 on 2024-02-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_alter_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='completed',
        ),
    ]
