# Generated by Django 4.2.6 on 2023-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_remove_pc_nome_pc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('c', 'Computador'), ('p', 'Periférico'), ('a', 'Acessório')], default='c', help_text='Categoria do produto', max_length=1),
        ),
    ]
