# Generated by Django 4.2.6 on 2023-10-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0008_remove_pc_imagem_remove_pc_preco_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='Sem imagem', upload_to='venda/static/images'),
        ),
    ]
