# Generated by Django 4.2.6 on 2024-02-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0008_alter_usuario_cep_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default='', max_length=100)),
                ('localidade', models.CharField(default='', max_length=100)),
                ('logradouro', models.CharField(default='', max_length=100)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='venda.endereco'),
        ),
    ]
