# Generated by Django 4.2.6 on 2023-10-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='Sem imagem', upload_to='images'),
        ),
    ]
