# Generated by Django 4.2.6 on 2024-02-22 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_endereco_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False),
        ),
    ]
