# Generated by Django 4.2.6 on 2024-02-22 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0010_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
