# Generated by Django 4.2.6 on 2023-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0012_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, max_length=50000),
        ),
        migrations.DeleteModel(
            name='InstanciaProduto',
        ),
    ]
