# Generated by Django 4.2.6 on 2023-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0013_produto_estoque_delete_instanciaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(help_text='Preço'),
        ),
    ]
