# Generated by Django 4.2.6 on 2024-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0014_alter_usuario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
