# Generated by Django 4.2.6 on 2023-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0016_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
