# Generated by Django 4.2.6 on 2023-11-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0017_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
