# Generated by Django 4.2.6 on 2023-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0020_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='media/perfil.png', upload_to=''),
        ),
    ]
