# Generated by Django 4.2.6 on 2023-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0021_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
