# Generated by Django 4.2.6 on 2023-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0024_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='media/perfil.png', upload_to='../media'),
        ),
    ]
